# Generated by Django 5.1.7 on 2025-03-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_salesitems_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='discount_amount',
            field=models.FloatField(default=0),
        ),
    ]
