# Generated by Django 5.1.2 on 2025-03-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='taxpercentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
