# Generated by Django 5.1.7 on 2025-03-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_products_taxpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code_bar',
            field=models.CharField(default='', max_length=100),
        ),
    ]
