# Generated by Django 5.1.7 on 2025-03-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_products_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code_bar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
