# Generated by Django 5.1.7 on 2025-04-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='type',
            field=models.IntegerField(choices=[(0, 'Quincaillerie'), (1, 'Meubles'), (2, 'Decoration'), (3, 'Electronique'), (4, 'Détailleur'), (5, 'Artisanat'), (6, 'Agriculture'), (7, 'Autres')]),
        ),
    ]
